#consulservice:
#  directory:
#    version: ${preload.version}
#    clientUri:
#      baseUri: http://localhost:8500
#      getUri: ${consulservice.directory.clientUri.baseUri}/v1/kv/config/common/{key}
#    preloadResponse: ${preload.response.${consulservice.directory.version}}
#    cardlessList:
#      cardless: ${cardless.${consulservice.directory.version}